### PR TITLE
Merge workflow features and bug fixes into master

### PR DESCRIPTION
**Pull request by bsmithyman**
This includes work from the 'db' branch, 'pragmatism', 'ani_testing', 'fix_wraparound', etc.

I think it's ready to merge, though there may be some cleanup to do.

### CODE REVIEW

**Comment by bsmithyman** [comment]
@ShaunHadden?

**Comment by ShaunHadden** [comment]
Hi Brendan,

Sorry I was TAing all day. Is there any other merge requests that I am missing?

**Comment by bsmithyman** [comment]
Don't think so; I've been cleaning up a lot of stuff. I just thought I'd check with you on this one.

**Comment by ShaunHadden** [comment]
Great Thanks, I looked through some of the issues you closed and agree that they were indeed solved! Thanks for doing that!

**Pull request merged**
